name: Android Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.version }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.19.6

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12'
      
      - name: Check a new tag
        id: tag
        run: |
          export TAG_VERSION=$(grep version pubspec.yaml |  awk -F  ': ' '{print $2}')
          echo "version=$TAG_VERSION<<EOF" >> $GITHUB_OUTPUT
          echo $TAG_VERSION
          git tag $TAG_VERSION
          git push origin $TAG_VERSION

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar

      - name: 'Append publish gradle script'
        run: |
          cat publish.gradle >> .android/build.gradle

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar --no-debug --no-profile --build-number ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

